In [1]:
# Input bags
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [44]:
# Input data
path='C:\\Users\\YWANG418\\Documents\\Job\\Machine Learning\\Regression\\longley.csv'
data=pd.read_csv(path,header=None)
x=data.iloc[1:,2:]
y=data.iloc[1:,1]
x=np.mat(x, dtype=float)
y=np.mat(y, dtype=float).T
X= np.concatenate((np.ones((16,1)),x),axis=1)

matrix([[ 83. ],
        [ 88.5],
        [ 88.2],
        [ 89.5],
        [ 96.2],
        [ 98.1],
        [ 99. ],
        [100. ],
        [101.2],
        [104.6],
        [108.4],
        [110.8],
        [112.6],
        [114.2],
        [115.7],
        [116.9]])

In [47]:
# Normal Equation Function
def weights(xArr, yArr,lam=0.2):
    xMat = np.mat(xArr)
    yMat = np.mat(yArr)
    xTx = xMat.T*xMat 
    rxTx=xTx+np.eye(xMat.shape[1])*lam
# np.eye generate a diagonal matrix
# rxTx is (xTx+ lam*I)
    # If det==0, there isn't inverse matrix
    if np.linalg.det(xTx) == 0.0:
        print("This matrix cannot do inverse")
        return
    # xTx.I is inverse matrix of xTx
    ws = rxTx.I*xMat.T*yMat
    return ws

In [48]:
ws=weights(X,y)
print(ws)

[[ 7.38107886e-04]
 [ 2.07703836e-01]
 [ 2.10076376e-02]
 [ 5.05385441e-03]
 [-1.59173066e+00]
 [ 1.10442920e-01]
 [-2.42280461e-01]]


In [50]:
# Predict 
X*np.mat(ws)


matrix([[ 83.55075226],
        [ 86.92588689],
        [ 88.09720228],
        [ 90.95677622],
        [ 96.06951002],
        [ 97.81955375],
        [ 98.36444357],
        [ 99.99814266],
        [103.26832266],
        [105.03165135],
        [107.45224671],
        [109.52190685],
        [112.91863666],
        [113.98357055],
        [115.29845063],
        [117.64279933]])